package hagrid.utils.general;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import hagrid.HagridPaths;
import hagrid.pipeline.ScenarioConfig;

/**
 * Generates a ready-to-execute {@code run_hagrid_sim.bat} from the current
 * pipeline scenario configuration and simulation settings.
 *
 * <p>The generated bat file contains all JDK paths, VM-arg references and
 * scenario arguments so the MATSim simulation can be started on the
 * simulation server without manual editing.</p>
 */
public final class SimulationBatGenerator {

	private static final Logger LOGGER = LogManager.getLogger(SimulationBatGenerator.class);

	/** Container for all simulation-level settings written into the bat args. */
	public record SimulationSettings(
			int maxIter,
			int jspritIter,
			boolean zoneCaching,
			int zoneThreshold,
			double uTurnPenalty,
			boolean writeDashboard
	) {}

	private SimulationBatGenerator() { /* utility */ }

	// =========================================================================
	// PUBLIC API
	// =========================================================================

	/**
	 * Generates {@code run_hagrid_sim.bat} with all scenario arguments pre-filled
	 * from the given scenarios and simulation settings.
	 *
	 * @param scenarios  the pipeline scenarios (concept / date / tag are extracted)
	 * @param settings   simulation-level parameters (maxIter, jspritIter, …)
	 */
	public static void generate(ScenarioConfig[] scenarios, SimulationSettings settings) {
		List<String> scenarioArgs = buildScenarioArgs(scenarios, settings);
		String batContent = buildBatContent(scenarioArgs);
		writeBatFile(batContent, scenarioArgs);
	}

	// =========================================================================
	// SCENARIO ARGS  (concept=X,date=Y,…)
	// =========================================================================

	private static List<String> buildScenarioArgs(ScenarioConfig[] scenarios, SimulationSettings s) {
		List<String> args = new ArrayList<>();
		DateTimeFormatter dateFmt = DateTimeFormatter.ISO_LOCAL_DATE;

		for (ScenarioConfig sc : scenarios) {
			for (String concept : sc.getConcepts()) {
				for (LocalDate date : sc.getDates()) {
					StringBuilder sb = new StringBuilder();
					sb.append("concept=").append(concept);
					sb.append(",date=").append(date.format(dateFmt));

					String tag = sc.getTag();
					if (tag != null && !tag.isEmpty()) {
						sb.append(",tag=").append(tag);
					}

					sb.append(",maxIter=").append(s.maxIter());
					sb.append(",jspritIter=").append(s.jspritIter());

					if (s.zoneCaching()) {
						sb.append(",zoneCaching=true");
						sb.append(",zoneThreshold=").append(s.zoneThreshold());
					}

					if (s.uTurnPenalty() != 1.0) {
						sb.append(",uTurnPenalty=").append(s.uTurnPenalty());
					}

					if (s.writeDashboard()) {
						sb.append(",writeDashboard=true");
					}

					args.add(sb.toString());
				}
			}
		}
		return args;
	}

	// =========================================================================
	// BAT FILE CONTENT
	// =========================================================================

	private static String buildBatContent(List<String> scenarioArgs) {
		StringBuilder bat = new StringBuilder();
		bat.append("@echo off\r\n");
		bat.append("setlocal\r\n");
		bat.append("\r\n");
		bat.append("cd /d \"%~dp0\"\r\n");
		bat.append("\r\n");
		bat.append("rem ═══════════════════════════════════════════════════════════════\r\n");
		bat.append("rem   Auto-generated by HAGRID2MATSimPipelineRunner\r\n");
		bat.append("rem   Scenarios and settings come from the pipeline configuration.\r\n");
		bat.append("rem ═══════════════════════════════════════════════════════════════\r\n");
		bat.append("\r\n");
		bat.append("rem harte Vorgabe JDK 21\r\n");
		bat.append("set \"JAVA_EXE=C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.3.9-hotspot\\bin\\java.exe\"\r\n");
		bat.append("\r\n");
		bat.append("rem evtl. Overrides entschaerfen\r\n");
		bat.append("set \"JAVA_TOOL_OPTIONS=\"\r\n");
		bat.append("set \"_JAVA_OPTIONS=\"\r\n");
		bat.append("set \"JDK_JAVA_OPTIONS=\"\r\n");
		bat.append("\r\n");
		bat.append("rem Sichtpruefung\r\n");
		bat.append("\"%JAVA_EXE%\" -version\r\n");
		bat.append("\r\n");
		bat.append("rem effektive VM Settings vor dem Start loggen\r\n");
		bat.append("if not exist \"hagrid-matsim-output\\logs\\jvm\" mkdir \"hagrid-matsim-output\\logs\\jvm\"\r\n");
		bat.append("\"%JAVA_EXE%\" -XshowSettings:vm -version 2> \"hagrid-matsim-output\\logs\\jvm\\vm_settings_before.txt\"\r\n");
		bat.append("\r\n");
		bat.append("rem JAR pruefen\r\n");
		bat.append("set \"JAR=target\\parcel-demand-2-matsim-pipeline-1.0-SNAPSHOT.jar\"\r\n");
		bat.append("if not exist \"%JAR%\" (\r\n");
		bat.append("  echo JAR not found %JAR%\r\n");
		bat.append("  exit /b 1\r\n");
		bat.append(")\r\n");
		bat.append("\r\n");
		bat.append("echo Starting with args from vmargs.txt\r\n");
		bat.append("type vmargs.txt\r\n");
		bat.append("\r\n");

		// One execution block per scenario
		for (int i = 0; i < scenarioArgs.size(); i++) {
			String arg = scenarioArgs.get(i);
			bat.append(String.format("rem ─── Scenario %d/%d ───\r\n", i + 1, scenarioArgs.size()));
			bat.append(String.format("set \"SCENARIO_%d=%s\"\r\n", i + 1, arg));
			bat.append("echo.\r\n");
			bat.append(String.format("echo Running scenario %d/%d: %%SCENARIO_%d%%\r\n", i + 1, scenarioArgs.size(), i + 1));
			bat.append(String.format("\"%sJAVA_EXE%s\" @vmargs.txt -Dhagrid.pipeline.root=. -jar \"%sJAR%s\" %%SCENARIO_%d%%\r\n",
					"%", "%", "%", "%", i + 1));
			bat.append(String.format("if %%ERRORLEVEL%% neq 0 (\r\n"));
			bat.append(String.format("  echo FAILED scenario %d with exit code %%ERRORLEVEL%%\r\n", i + 1));
			bat.append(String.format("  set \"FAILURES=%%FAILURES%% %d\"\r\n", i + 1));
			bat.append(")\r\n");
			bat.append("\r\n");
		}

		bat.append("if defined FAILURES (\r\n");
		bat.append("  echo.\r\n");
		bat.append("  echo WARNING: Failed scenarios: %FAILURES%\r\n");
		bat.append("  exit /b 1\r\n");
		bat.append(")\r\n");
		bat.append("\r\n");
		bat.append("echo.\r\n");
		bat.append(String.format("echo All %d scenario(s) completed successfully.\r\n", scenarioArgs.size()));
		bat.append("\r\n");
		bat.append("endlocal\r\n");
		bat.append("exit /b 0\r\n");

		return bat.toString();
	}

	// =========================================================================
	// FILE OUTPUT
	// =========================================================================

	private static void writeBatFile(String content, List<String> scenarioArgs) {
		// Use HagridPaths auto-detection to find the pipeline root
		Path pipelineRoot = new HagridPaths().getPipelineRoot();
		Path batFile = pipelineRoot.resolve("run_hagrid_sim.bat");
		try {
			Files.writeString(batFile, content, StandardCharsets.UTF_8);
			LOGGER.info("Generated simulation bat file: {}", batFile.toAbsolutePath());
			LOGGER.info("  {} scenario(s) configured:", scenarioArgs.size());
			for (int i = 0; i < scenarioArgs.size(); i++) {
				LOGGER.info("    [{}] {}", i + 1, scenarioArgs.get(i));
			}
		} catch (IOException e) {
			LOGGER.warn("Could not write simulation bat file: {}", e.getMessage());
		}
	}
}
