@echo off
setlocal

cd /d "%~dp0"

rem ═══════════════════════════════════════════════════════════════
rem   Auto-generated by HAGRID2MATSimPipelineRunner
rem   Scenarios and settings come from the pipeline configuration.
rem ═══════════════════════════════════════════════════════════════

rem harte Vorgabe JDK 21
set "JAVA_EXE=C:\Program Files\Eclipse Adoptium\jdk-21.0.3.9-hotspot\bin\java.exe"

rem evtl. Overrides entschaerfen
set "JAVA_TOOL_OPTIONS="
set "_JAVA_OPTIONS="
set "JDK_JAVA_OPTIONS="

rem Sichtpruefung
"%JAVA_EXE%" -version

rem effektive VM Settings vor dem Start loggen
if not exist "hagrid-matsim-output\logs\jvm" mkdir "hagrid-matsim-output\logs\jvm"
"%JAVA_EXE%" -XshowSettings:vm -version 2> "hagrid-matsim-output\logs\jvm\vm_settings_before.txt"

rem JAR pruefen
set "JAR=target\parcel-demand-2-matsim-pipeline-1.0-SNAPSHOT.jar"
if not exist "%JAR%" (
  echo JAR not found %JAR%
  exit /b 1
)

echo Starting with args from vmargs.txt
type vmargs.txt

rem ─── Scenario 1/10 ───
set "SCENARIO_1=concept=basecase,date=2025-05-13,tag=60v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 1/10: %SCENARIO_1%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_1%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 1 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 1"
)

rem ─── Scenario 2/10 ───
set "SCENARIO_2=concept=basecase,date=2025-05-13,tag=70v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 2/10: %SCENARIO_2%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_2%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 2 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 2"
)

rem ─── Scenario 3/10 ───
set "SCENARIO_3=concept=basecase,date=2025-05-13,tag=80v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 3/10: %SCENARIO_3%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_3%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 3 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 3"
)

rem ─── Scenario 4/10 ───
set "SCENARIO_4=concept=basecase,date=2025-05-13,tag=90v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 4/10: %SCENARIO_4%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_4%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 4 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 4"
)

rem ─── Scenario 5/10 ───
set "SCENARIO_5=concept=basecase,date=2025-05-13,tag=100v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 5/10: %SCENARIO_5%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_5%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 5 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 5"
)

rem ─── Scenario 6/10 ───
set "SCENARIO_6=concept=basecase,date=2025-05-13,tag=110v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 6/10: %SCENARIO_6%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_6%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 6 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 6"
)

rem ─── Scenario 7/10 ───
set "SCENARIO_7=concept=basecase,date=2025-05-13,tag=120v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 7/10: %SCENARIO_7%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_7%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 7 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 7"
)

rem ─── Scenario 8/10 ───
set "SCENARIO_8=concept=basecase,date=2025-05-13,tag=130v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 8/10: %SCENARIO_8%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_8%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 8 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 8"
)

rem ─── Scenario 9/10 ───
set "SCENARIO_9=concept=basecase,date=2025-05-13,tag=140v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 9/10: %SCENARIO_9%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_9%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 9 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 9"
)

rem ─── Scenario 10/10 ───
set "SCENARIO_10=concept=basecase,date=2025-05-13,tag=150v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 10/10: %SCENARIO_10%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_10%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 10 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 10"
)

if defined FAILURES (
  echo.
  echo WARNING: Failed scenarios: %FAILURES%
  exit /b 1
)

echo.
echo All 10 scenario(s) completed successfully.

endlocal
exit /b 0
