package hagrid.utils.general;

    // Region enumeration
    public enum Region {
        BARSINGHAUSEN, BURGDORF, BURGWEDEL, GARBSEN, GEHRDEN, HANNOVER, HEMMINGEN,
        ISERNHAGEN, LAATZEN, LANGENHAGEN, LEHRTE, NEUSTADT, PATTENSEN, RONNENBERG,
        SEELZE, SEHNDE, SPRINGE, UETZE, WEDEMARK, WENNIGSEN, WUNSTORF, ALL
    }
