@echo off
setlocal

cd /d "%~dp0"

rem ═══════════════════════════════════════════════════════════════
rem   Auto-generated by HAGRID2MATSimPipelineRunner
rem   Scenarios and settings come from the pipeline configuration.
rem ═══════════════════════════════════════════════════════════════

rem JDK aufloesen: HAGRID_JAVA_EXE > JAVA_HOME > PATH (JDK 21 erwartet)
set "JAVA_EXE="
if defined HAGRID_JAVA_EXE if exist "%HAGRID_JAVA_EXE%" set "JAVA_EXE=%HAGRID_JAVA_EXE%"
if not defined JAVA_EXE if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" set "JAVA_EXE=%JAVA_HOME%\bin\java.exe"
if not defined JAVA_EXE for %%J in (java.exe) do set "JAVA_EXE=%%~$PATH:J"
if not defined JAVA_EXE (
  echo No java.exe found. Set JAVA_HOME or HAGRID_JAVA_EXE to a JDK 21 installation.
  exit /b 1
)
echo Using JAVA_EXE=%JAVA_EXE%

rem evtl. Overrides entschaerfen
set "JAVA_TOOL_OPTIONS="
set "_JAVA_OPTIONS="
set "JDK_JAVA_OPTIONS="

rem Sichtpruefung
"%JAVA_EXE%" -version

rem effektive VM Settings vor dem Start loggen
if not exist "hagrid-matsim-output\logs\jvm" mkdir "hagrid-matsim-output\logs\jvm"
"%JAVA_EXE%" -XshowSettings:vm -version 2> "hagrid-matsim-output\logs\jvm\vm_settings_before.txt"

rem Versionspruefung: MATSim/HAGRID sind auf 21 gebaut (pom.xml release=21)
findstr /r /c:"version .21\." "hagrid-matsim-output\logs\jvm\vm_settings_before.txt" >nul
if errorlevel 1 echo WARNING: JDK 21 expected - see hagrid-matsim-output\logs\jvm\vm_settings_before.txt

rem JAR pruefen
set "JAR=target\parcel-demand-2-matsim-pipeline-1.0-SNAPSHOT.jar"
if not exist "%JAR%" (
  echo JAR not found %JAR%
  exit /b 1
)

echo Starting with args from vmargs.txt
type vmargs.txt

rem ─── Scenario 1/26 ───
set "SCENARIO_1=concept=basecase,date=2025-05-13,tag=160v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 1/26: %SCENARIO_1%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_1%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 1 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 1"
)

rem ─── Scenario 2/26 ───
set "SCENARIO_2=concept=basecase,date=2025-05-13,tag=170v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 2/26: %SCENARIO_2%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_2%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 2 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 2"
)

rem ─── Scenario 3/26 ───
set "SCENARIO_3=concept=basecase,date=2025-05-13,tag=180v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 3/26: %SCENARIO_3%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_3%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 3 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 3"
)

rem ─── Scenario 4/26 ───
set "SCENARIO_4=concept=basecase,date=2025-05-13,tag=190v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 4/26: %SCENARIO_4%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_4%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 4 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 4"
)

rem ─── Scenario 5/26 ───
set "SCENARIO_5=concept=basecase,date=2025-05-13,tag=200v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 5/26: %SCENARIO_5%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_5%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 5 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 5"
)

rem ─── Scenario 6/26 ───
set "SCENARIO_6=concept=basecase,date=2025-05-13,tag=210v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 6/26: %SCENARIO_6%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_6%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 6 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 6"
)

rem ─── Scenario 7/26 ───
set "SCENARIO_7=concept=basecase,date=2025-05-13,tag=220v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 7/26: %SCENARIO_7%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_7%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 7 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 7"
)

rem ─── Scenario 8/26 ───
set "SCENARIO_8=concept=basecase,date=2025-05-13,tag=230v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 8/26: %SCENARIO_8%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_8%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 8 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 8"
)

rem ─── Scenario 9/26 ───
set "SCENARIO_9=concept=basecase,date=2025-05-13,tag=240v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 9/26: %SCENARIO_9%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_9%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 9 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 9"
)

rem ─── Scenario 10/26 ───
set "SCENARIO_10=concept=basecase,date=2025-05-13,tag=250v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 10/26: %SCENARIO_10%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_10%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 10 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 10"
)

rem ─── Scenario 11/26 ───
set "SCENARIO_11=concept=basecase,date=2025-05-13,tag=260v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 11/26: %SCENARIO_11%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_11%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 11 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 11"
)

rem ─── Scenario 12/26 ───
set "SCENARIO_12=concept=basecase,date=2025-05-13,tag=270v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 12/26: %SCENARIO_12%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_12%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 12 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 12"
)

rem ─── Scenario 13/26 ───
set "SCENARIO_13=concept=basecase,date=2025-05-13,tag=280v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 13/26: %SCENARIO_13%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_13%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 13 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 13"
)

rem ─── Scenario 14/26 ───
set "SCENARIO_14=concept=basecase,date=2025-05-13,tag=290v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 14/26: %SCENARIO_14%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_14%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 14 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 14"
)

rem ─── Scenario 15/26 ───
set "SCENARIO_15=concept=basecase,date=2025-05-13,tag=300v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 15/26: %SCENARIO_15%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_15%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 15 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 15"
)

rem ─── Scenario 16/26 ───
set "SCENARIO_16=concept=basecase,date=2025-05-13,tag=310v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 16/26: %SCENARIO_16%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_16%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 16 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 16"
)

rem ─── Scenario 17/26 ───
set "SCENARIO_17=concept=basecase,date=2025-05-13,tag=320v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 17/26: %SCENARIO_17%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_17%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 17 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 17"
)

rem ─── Scenario 18/26 ───
set "SCENARIO_18=concept=basecase,date=2025-05-13,tag=330v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 18/26: %SCENARIO_18%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_18%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 18 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 18"
)

rem ─── Scenario 19/26 ───
set "SCENARIO_19=concept=basecase,date=2025-05-13,tag=340v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 19/26: %SCENARIO_19%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_19%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 19 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 19"
)

rem ─── Scenario 20/26 ───
set "SCENARIO_20=concept=basecase,date=2025-05-13,tag=350v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 20/26: %SCENARIO_20%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_20%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 20 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 20"
)

rem ─── Scenario 21/26 ───
set "SCENARIO_21=concept=basecase,date=2025-05-13,tag=360v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 21/26: %SCENARIO_21%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_21%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 21 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 21"
)

rem ─── Scenario 22/26 ───
set "SCENARIO_22=concept=basecase,date=2025-05-13,tag=370v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 22/26: %SCENARIO_22%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_22%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 22 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 22"
)

rem ─── Scenario 23/26 ───
set "SCENARIO_23=concept=basecase,date=2025-05-13,tag=380v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 23/26: %SCENARIO_23%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_23%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 23 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 23"
)

rem ─── Scenario 24/26 ───
set "SCENARIO_24=concept=basecase,date=2025-05-13,tag=390v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 24/26: %SCENARIO_24%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_24%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 24 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 24"
)

rem ─── Scenario 25/26 ───
set "SCENARIO_25=concept=basecase,date=2025-05-13,tag=400v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 25/26: %SCENARIO_25%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_25%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 25 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 25"
)

rem ─── Scenario 26/26 ───
set "SCENARIO_26=concept=basecase,date=2025-05-13,tag=70v2,maxIter=150,jspritIter=1000,zoneCaching=true,zoneThreshold=1500,writeDashboard=true"
echo.
echo Running scenario 26/26: %SCENARIO_26%
"%JAVA_EXE%" @vmargs.txt -Dhagrid.pipeline.root=. -jar "%JAR%" %SCENARIO_26%
if %ERRORLEVEL% neq 0 (
  echo FAILED scenario 26 with exit code %ERRORLEVEL%
  set "FAILURES=%FAILURES% 26"
)

if defined FAILURES (
  echo.
  echo WARNING: Failed scenarios: %FAILURES%
  exit /b 1
)

echo.
echo All 26 scenario(s) completed successfully.

endlocal
exit /b 0
